# config/meta.yml

meta_product_name: "Node labz"
meta_title: "Node labz - Create your custom gaming computer."
meta_description: "The ultimate path to your dream gaming machine."
meta_image: "http://thebubbashow.org/wp-content/uploads/2017/03/google-police.jpg"  # should exist in `app/assets/images/`
