# config/meta.yml

meta_product_name: "Node Labs"
meta_title: "Node Labs - The ultimate path to your dream gaming machine."
meta_description: "Create your custom gaming computer with a few simple steps.
No experience? No worries."
meta_image: "og-image-v1.png"
twitter_account: "@be_mika"